export const MEDICINES = [
  {
    id: 1,
    name: 'AC. VALPROICO',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 2,
    name: 'AC. FOLINICO 50',
    presentation: 12.5,
    administrationTime: '30 MIN',
    concentration: 0.5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 3,
    name: 'AC. FOLINICO 15',
    presentation: 3,
    administrationTime: '30 MIN',
    concentration: 0.5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 4,
    name: 'ACICLOVIR',
    presentation: 25,
    administrationTime: '90 MIN',
    concentration: 2,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 5,
    name: 'ALBUMINA 25%',
    presentation: 0.2,
    administrationTime: '240 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 6,
    name: 'ALBUMINA 20%',
    presentation: 0.25,
    administrationTime: '240 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 7,
    name: 'ANFOTERICINA B LIP',
    presentation: 5,
    administrationTime: '120 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION GLUCOSADA AL 5%',
  },
  {
    id: 8,
    name: 'ANFOTERICINA B CONV',
    presentation: 5,
    administrationTime: '120 MIN',
    concentration: 0.1,
    diluent: 'AFORAR CON SOLUCION GLUCOSADA AL 5%',
  },
  {
    id: 9,
    name: 'AMIKACINA',
    presentation: 250,
    administrationTime: '30 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 10,
    name: 'AMIKACINA',
    presentation: 50,
    administrationTime: '30 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 11,
    name: 'AMIODARONA',
    presentation: 50,
    administrationTime: '60 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 12,
    name: 'AMPICILINA',
    presentation: 200,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 13,
    name: 'AMPICILINA',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 14,
    name: 'AMPICILINA',
    presentation: 50,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 15,
    name: 'BUTILHIOSCINA',
    presentation: 20,
    administrationTime: '5 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 16,
    name: 'BUMETANIDA',
    presentation: 0.25,
    administrationTime: null,
    concentration: 0.024,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 17,
    name: 'BUPRENORFINA',
    presentation: 300,
    administrationTime: '5 MIN',
    concentration: 15,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 18,
    name: 'DICLOFENACO',
    presentation: 25,
    administrationTime: '30 MIN',
    concentration: 2,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 19,
    name: 'CASPOFUNGINA',
    presentation: 5,
    administrationTime: '240 MIN',
    concentration: 0.5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 20,
    name: 'CEFALOTINA',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 50,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 21,
    name: 'CEFEPIMA',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 40,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 22,
    name: 'CEFOTAXIMA',
    presentation: 250,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 23,
    name: 'CEFTAZIDIMA',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 24,
    name: 'CEFTRIAXONA',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 25,
    name: 'CEFUROXIMA',
    presentation: 150,
    administrationTime: '30 MIN',
    concentration: 30,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 26,
    name: 'CIPROFLOXACINO',
    presentation: 2,
    administrationTime: '60 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 27,
    name: 'CLINDAMICINA',
    presentation: 150,
    administrationTime: '30 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 28,
    name: 'COLISTIMETATO',
    presentation: 30,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 29,
    name: 'CLOROPIRAMINA',
    presentation: 10,
    administrationTime: '15 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 30,
    name: 'DEXAMETASONA',
    presentation: 4,
    administrationTime: '3 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 31,
    name: 'DEXAMETASONA DEPOT',
    presentation: 4,
    administrationTime: '1 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 32,
    name: 'DEXMEDETOMIDINA',
    presentation: 100,
    administrationTime: '10 MIN',
    concentration: 4,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 33,
    name: 'DIFENIDOL',
    presentation: 20,
    administrationTime: '15 MIN',
    concentration: 2,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 34,
    name: 'DIFENHIDRAMINA',
    presentation: 10,
    administrationTime: '15 MIN',
    concentration: 2,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 35,
    name: 'ETAMSILATO',
    presentation: 125,
    administrationTime: '30 MIN',
    concentration: null,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 36,
    name: 'ENOXAPARINA',
    presentation: 100,
    administrationTime: '1 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 37,
    name: 'ERITROPOYETINA',
    presentation: 2000,
    administrationTime: '1 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 38,
    name: 'ERITROPOYETINA',
    presentation: 4000,
    administrationTime: '1 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 39,
    name: 'FENITOINA',
    presentation: 50,
    administrationTime: '5 MIN',
    concentration: 6,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 40,
    name: 'FILGRASTIM',
    presentation: 300,
    administrationTime: '1 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 41,
    name: 'FLUCONAZOL',
    presentation: 2,
    administrationTime: '120 MIN',
    concentration: 2,
    diluent: null,
  },
  {
    id: 42,
    name: 'FOSAPREPITANT',
    presentation: 30,
    administrationTime: '30 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 43,
    name: 'FUROSEMIDA',
    presentation: 10,
    administrationTime: '5 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 44,
    name: 'FOSFOMICINA',
    presentation: 100,
    administrationTime: '60 MIN',
    concentration: 20,
    diluent: 'AFORAR CON SOLUCION GLUCOSADA AL 5%',
  },
  {
    id: 45,
    name: 'GANCICLOVIR',
    presentation: 5,
    administrationTime: '60 MIN',
    concentration: null,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 46,
    name: 'GENTAMICINA',
    presentation: 80,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 47,
    name: 'GENTAMICINA',
    presentation: 40,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 48,
    name: 'GENTAMICINA',
    presentation: 10,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 49,
    name: 'HIDROCORTISONA',
    presentation: 20,
    administrationTime: '5 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 50,
    name: 'HIDROCORTISONA',
    presentation: 100,
    administrationTime: '5 MIN',
    concentration: 20,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 51,
    name: 'HIDRALAZINA',
    presentation: 20,
    administrationTime: '5 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 52,
    name: 'KETOROLACO',
    presentation: 30,
    administrationTime: '3 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 53,
    name: 'LINEZOLID',
    presentation: 2,
    administrationTime: '120 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 54,
    name: 'LEVOFLOXACINO',
    presentation: 5,
    administrationTime: '60 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 55,
    name: 'MEROPENEM',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: 20,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 56,
    name: 'METAMIZOL',
    presentation: 500,
    administrationTime: '30 MIN',
    concentration: 10,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 57,
    name: 'METILPREDNISOLONA',
    presentation: 50,
    administrationTime: '3 MIN',
    concentration: 20,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 58,
    name: 'METOCLOPRAMIDA',
    presentation: 5,
    administrationTime: '15 MIN',
    concentration: 0.2,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 59,
    name: 'METRONIDAZOL',
    presentation: 5,
    administrationTime: '30 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 60,
    name: 'METRONIDAZOL',
    presentation: 20,
    administrationTime: '30 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 61,
    name: 'OMEPRAZOL',
    presentation: 4,
    administrationTime: '15 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 62,
    name: 'ONDANSETRON',
    presentation: 2,
    administrationTime: '15 MIN',
    concentration: 0.16,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 63,
    name: 'OCTREOTIDA',
    presentation: 0.2,
    administrationTime: 'CONTINUA',
    concentration: 0.025,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 64,
    name: 'PARACETAMOL',
    presentation: 100,
    administrationTime: '30 MIN',
    concentration: null,
    diluent: null,
  },
  {
    id: 65,
    name: 'PIPERACILINA',
    presentation: 200,
    administrationTime: '30 MIN',
    concentration: 20,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 66,
    name: 'TRAMADOL',
    presentation: 50,
    administrationTime: '20 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 67,
    name: 'TRIMETOPRIM',
    presentation: 53.33,
    administrationTime: '60 MIN',
    concentration: 2,
    diluent: 'AFORAR CON SOLUCION GLUCOSADA AL 5%',
  },
  {
    id: 68,
    name: 'TIGECICLINA',
    presentation: 10,
    administrationTime: '60 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 69,
    name: 'TEICOPLANINA',
    presentation: 40,
    administrationTime: '120 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 70,
    name: 'TEICOPLANINA',
    presentation: 80,
    administrationTime: '120 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 71,
    name: 'VANCOMICINA',
    presentation: 50,
    administrationTime: '120 MIN',
    concentration: 2.5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 72,
    name: 'FITOMENADIONA',
    presentation: 10,
    administrationTime: '10 MIN',
    concentration: 1,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 73,
    name: 'VORICONAZOL',
    presentation: 10,
    administrationTime: '60 MIN',
    concentration: 2.5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
  {
    id: 74,
    name: 'LEVETIRACETAM',
    presentation: 100,
    administrationTime: '15 MIN',
    concentration: 5,
    diluent: 'AFORAR CON SOLUCION FISIOLÒGICA 0.9%',
  },
];
